os: linux
php: 7.1
dist: trusty
sudo: false
cache:
    directories:
        - $HOME/.composer/cache/files
group: stable
script:
    - composer install
    - ls -la
    - cat config/routes.yaml
    - cat public/index.php
    - cat .env
language: php