os: linux
php: 7.1
dist: trusty
sudo: false
cache:
    directories:
        - $HOME/.composer/cache/files
group: stable
script:
    - composer create-project mukadi/wp-sf-skeleton app
    - cd app
    - ls -la
    - cat config/routes.yaml
    - cat public/index.php
    - cat .env
    - cat .gitignore
language: php